# defining a multi-service Docker stack with a Neo4j 5.20-enterprise database (APOC & GDS plugins, persistent volume), a FastAPI backend depending 
# on Neo4j, and a React frontend depending on the backend, each exposed on their respective ports.

# version: "3.8"
services:
  neo4j:
    # image: neo4j:5.6
    image: neo4j:5.20-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"    # Browser
      - "7687:7687"    # Bolt
    environment:
      # NEO4J_AUTH: "neo4j/password"
      NEO4J_AUTH:              "neo4j/password"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS:       '["apoc","graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - ./import:/import    # for  CSV  => file:///emails.csv

  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  neo4j_data:
